### ISSUE TITLE
Mail movement options menu not shows

### ISSUE THREAD

**Issue by evolic** [flightjs/example-app#5]
Hi there,

I noticed that if you click on the row (mail item) and you click on the `move` menu - you will get the options (http://flightjs.github.io/example-app/#).

But if you don't choose any and click again on the `move` menu - options will not show (mail is selected and highlighted).

When I click on the `move` menu and click somewhere else - menu disappears, and when I click again on the `move` menu - menu shows up... so it is working good.

--
Very best,
Tomasz Kuter

**Comment by phuu** [comment]
Closing as we're going to build a new app.
